config:
  plugins:
    metrics-by-endpoint: {}
  target: 'http://localhost:8080'
  phases:
    - duration: 20 # duración total 20 segs
      arrivalRate: 10 # 10 usuarios virtuales por seg
scenarios:
  - name: "Sessions Flow (api/marketplace)"
    flow:
      - log: "Creating variables for user"
      - get:
          url: '/api/auth/users'
          capture:
            - json: "$.name"
              as: "name"
            - json: "$.lastName"
              as: "lastName"
            - json: "$.email"
              as: "email"
            - json: "$.gender"
              as: "gender"
            - json: "$.password"
              as: "password"
      - log: "Registering user"
      - post:
          url: "/api/auth/register"
          json:
            name: "{{ name }}"
            lastName: "{{ lastName }}"
            email: "{{ email }}"
            gender: "{{ gender }}"
            password: "{{ password }}"
      - think: 2
      - log: "Login user"
      - post:
          url: "/api/auth/jwtlogin"
          json:
            email: "{{ email }}"
            password: "{{ password }}"
